// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function CountToken(arg1) {
  return window['go']['main']['App']['CountToken'](arg1);
}

export function Dummy1() {
  return window['go']['main']['App']['Dummy1']();
}
