// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sydney} from '../models';

export function AskAI(arg1:main.AskOptions):Promise<void>;

export function CheckUpdate():Promise<main.CheckUpdateResult>;

export function CountToken(arg1:string):Promise<number>;

export function Dummy1():Promise<main.ChatFinishResult>;

export function FetchWebpage(arg1:string):Promise<main.FetchWebpageResult>;

export function GenerateImage(arg1:sydney.GenerativeImage):Promise<sydney.GenerateImageResult>;

export function GetUser():Promise<string>;

export function UploadDocument():Promise<main.UploadSydneyDocumentResult>;

export function UploadSydneyImage():Promise<main.UploadSydneyImageResult>;
