// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CountToken(arg1) {
  return window['go']['main']['App']['CountToken'](arg1);
}

export function Dummy1() {
  return window['go']['main']['App']['Dummy1']();
}

export function ExportWorkspace(arg1) {
  return window['go']['main']['App']['ExportWorkspace'](arg1);
}

export function FetchWebpage(arg1) {
  return window['go']['main']['App']['FetchWebpage'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['App']['GenerateImage'](arg1);
}

export function GenerateMusic(arg1) {
  return window['go']['main']['App']['GenerateMusic'](arg1);
}

export function GetConciseAnswer(arg1) {
  return window['go']['main']['App']['GetConciseAnswer'](arg1);
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function SaveRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRemoteFile'](arg1, arg2, arg3);
}

export function SaveRemoteJPEGImage(arg1) {
  return window['go']['main']['App']['SaveRemoteJPEGImage'](arg1);
}

export function SelectUploadFile() {
  return window['go']['main']['App']['SelectUploadFile']();
}

export function ShareWorkspace(arg1) {
  return window['go']['main']['App']['ShareWorkspace'](arg1);
}

export function UploadDocument() {
  return window['go']['main']['App']['UploadDocument']();
}

export function UploadSydneyImage() {
  return window['go']['main']['App']['UploadSydneyImage']();
}
